import React, { useState, useEffect } from "react";
import Principal from "./components/Principal";
import SeleccionDeDatos from "./components/SeleccionDeDatos";
import Calculos from "./components/Calculos";
import GraficaDeIntervalos from "./components/GraficaDeIntervalos";
import InfoPanel from "./components/InfoPanel";
import DataDisplay from "./components/DataDisplay";


//el app.js es el componente raiz de la aplicacion que gestiona y llama los componentes 
const App = () => {
  const [userName, setUserName] = useState("");
  const [dataReady, setDataReady] = useState(false);
  const [stats, setStats] = useState(null);
  const [showNameForm, setShowNameForm] = useState(false);

  //comento para que inicie siempre desde inicio de la parte del nombre
  // useEffect(() => {
  //   const savedName = localStorage.getItem("userName");
  //   if (savedName) {
  //     setUserName(savedName);
  //   }
  // }, []);

  const handleDataReady = (data) => {
    if (
      data &&
      typeof data.mean === "number" &&
      typeof data.stdDev === "number" &&
      data.sampleSize > 0
    ) {
      setStats(data);
      setDataReady(true);
    }
  };

  const handleResetData = () => {
    setDataReady(false);
    setStats(null);
  };

  const handleChangeName = () => {
    setShowNameForm(true);
  };

  const handleNameSubmit = (name) => {
    setUserName(name);
    setShowNameForm(false);
    localStorage.setItem("userName", name);
  };

  const resetApp = () => {
    setUserName("");
    setDataReady(false);
    setStats(null);
    localStorage.removeItem("userName");
  };

    // const handleBackToWelcome = () => {
    //   setDataReady(false);
    //   setStats(null);
    // };

  if (showNameForm) {
    return (
      <Principal onNameSubmit={handleNameSubmit} initialName={userName} />
    );
  }

  if (!userName) {
    return <Principal onNameSubmit={handleNameSubmit} />;
  }

  if (!dataReady) {
    return (
      //imagen con color
      <div
        className="min-h-screen bg-gray-50"
        style={{
          backgroundImage:
            "url('https://4tsix0yujj.ufs.sh/f/2vMRHqOYUHc0om3zHsOgDjdvqUQH6XhKYIiaSc3LCtrM1fen')",
          backgroundSize: "cover",
          backgroundPosition: "center",
          backgroundAttachment: "fixed",
          backgroundBlendMode: "overlay",
          backgroundColor: "rgba(255, 255, 255, 0.9)",
        }}
      >
        <SeleccionDeDatos
          userName={userName}
          onDataReady={handleDataReady}
          onBack={handleChangeName}
        />
      </div>
    );
  }

  return (
    <div
      className="min-h-screen bg-gray-50"
      style={{
        backgroundImage:
        //imagen sin color 
          "url('https://4tsix0yujj.ufs.sh/f/2vMRHqOYUHc0om3zHsOgDjdvqUQH6XhKYIiaSc3LCtrM1fen')",
        backgroundSize: "cover",
        backgroundPosition: "center",
        backgroundAttachment: "fixed",
        backgroundBlendMode: "overlay",
        backgroundColor: "rgba(255, 255, 255, 0.9)",
      }}
    >
      <div className="max-w-4xl mx-auto py-8 px-4">
        <header className="mb-8 bg-white rounded-xl shadow-lg p-6 backdrop-blur-sm bg-opacity-90 border border-gray-200">
          <div className="flex justify-between items-center">
            <div>
              <h1 className="text-3xl font-bold text-gray-800 font-serif">
                Intervalos De ConfianzaPro
              </h1>
              <p className="text-gray-600 mt-1">
                Usuario:{" "}
                <span className="font-medium text-blue-600">{userName}</span>
              </p>
            </div>
            <div className="flex gap-3">
              <button
                onClick={handleChangeName}
                className="text-sm bg-blue-600 hover:bg-blue-700 text-white py-2 px-4 rounded-lg transition-colors shadow-md"
              >
                Cambiar usuario
              </button>
              <button
                onClick={resetApp}
                className="text-sm bg-gray-600 hover:bg-gray-700 text-white py-2 px-4 rounded-lg transition-colors shadow-md"
              >
                Reiniciar todo
              </button>
            </div>
          </div>
        </header>

        <main className="space-y-6">
          {stats?.generatedData && <DataDisplay data={stats.generatedData} />}

          <Calculos
            initialMean={stats?.mean || 0}
            initialStdDev={stats?.stdDev || 0}
            initialSampleSize={stats?.sampleSize || 0}
            isAutoGenerated={!!stats?.generatedData}
          />

          {stats && (
            <GraficaDeIntervalos
              interval={{
                lower:
                  stats.mean -
                  1.96 * (stats.stdDev / Math.sqrt(stats.sampleSize)),
                upper:
                  stats.mean +
                  1.96 * (stats.stdDev / Math.sqrt(stats.sampleSize)),
              }}
            />
          )}

          <InfoPanel />

          <div className="flex gap-4 justify-center">
            <button
              onClick={handleResetData}
              className="bg-blue-600 hover:bg-blue-700 text-white font-medium py-3 px-8 rounded-lg transition-colors shadow-md flex items-center gap-2"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-5 w-5"
                viewBox="0 0 20 20"
                fill="currentColor"
              >
                <path
                  fillRule="evenodd"
                  d="M4 2a1 1 0 011 1v2.101a7.002 7.002 0 0111.601 2.566 1 1 0 11-1.885.666A5.002 5.002 0 005.999 7H9a1 1 0 010 2H4a1 1 0 01-1-1V3a1 1 0 011-1zm.008 9.057a1 1 0 011.276.61A5.002 5.002 0 0014.001 13H11a1 1 0 110-2h5a1 1 0 011 1v5a1 1 0 11-2 0v-2.101a7.002 7.002 0 01-11.601-2.566 1 1 0 01.61-1.276z"
                  clipRule="evenodd"
                />
              </svg>
              Nueva prueba
            </button>
          </div>
        </main>
      </div>
    </div>
  );
};

export default App;


